# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ace8b4ea47f2e515d8a9eb25778ad0929d9a54b432007dad95f726e87b8f3f42ca1ba4ca22c5daf138e14979fe4fa82bcb21bb612017404751fc055dfff3b761

test:
  secret_key_base: 0486b0d0689336ba248d72d63c6c1141e1dd90b1d400370dd7501efb660fa5e8be46684de8e8986e2473a20752b7b91c73a74052beda43fffbf5adfdf49060f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
